apiVersion: v2
name: sonarr
annotations:
  app: sonarr
description: Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
type: application
keywords:
  - servarr
  - sonarr
  - movies
  - management
  - web
  - http
version: 0.1.22
appVersion: "nightly"
icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/256.png
home: https://sonarr.video/
sources: 
  - https://github.com/Sonarr/Sonarr
  - https://github.com/gh4-io/thin-client-charts
  - https://wiki.servarr.com/sonarr
