apiVersion: v2
name: readarr
description: A Helm chart for Kubernetes

annotations:
  app: readarr

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.6

keywords:
  - servarr
  - readarr
  - books
  - magazines
  - reading
  - management
  - web
  - http

home: https://readarr.com/

sources:
  - https://hub.docker.com/r/linuxserver/readarr
  - https://github.com/gh4-io/thin-client-charts
  - https://github.com/Readarr/Readarr

icon: https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/256.png

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"
dependencies:
  - name: common
    version: 0.1.2
    repository: https://gh4-io.github.io/common-library-chart/