{{- if ( .Values.service.enabled | default false ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8989 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sonarr.selectorLabels" . | nindent 4 }}
{{- end -}}
