{{- if ( .Values.service.enabled | default false ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 9696 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prowlarr.selectorLabels" . | nindent 4 }}
{{- end -}}
